### ISSUE TITLE
Supermarket take over 

### ISSUE THREAD

**Issue by acaiafa** [apsoto/monit#66]
Hey guys. I have a monit cookbook that follows more current library patterns and am wondering if you don't mind if I take over ownership. I chatted with @aposto and he said he didn't mind and just to mention it in here so everyone can see if that's ok. Let me know thanks!

**Comment by freerobby** [comment]
@acaiafa I think @apsoto has been looking for a more regular maintainer for a while. Certainly no objections on my account if you want to take over.

If your cookbook is a major departure from how apsoto/monit works, it may be better to link to it from here so that people pulling straight from Github don't get something unexpected after building on top of @apsoto's version. I'll let you and @apsoto make that determination. If you do push your work to master on this repo, please make it clear in the README that there are significant changes to your version, and please do a major bump, to ensure as few upgrade hitches as possible.

**Comment by acaiafa** [comment]
Yeah sure I don't mind. If you want to take a look it's currently at
https://github.com/acaiafa/monit-cookbook

**Comment by apsoto** [comment]
Good luck....definitely be careful with versioning.  I would say you should add some sort of compatibility with previous versions and formats of attributes so folks who upgrade don't just fail.  If you detect 'old version' attributes you should complain loudly.  I hate it when upgrading cookbooks and things break with just stack traces.

**Comment by apsoto** [comment]
FYI - I _have not_ maintained this cookbook in years.  Other collaborators have commit access to maintain things.

**Comment by apsoto** [comment]
I've initiated the ownership transfer to @acaiafa
